name: Build & Security Check

on:
  push:
    branches: [ main, master, develop ]
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for better secret detection

      - name: Ensure .gitignore exists
        run: |
          echo "📝 Checking for .gitignore file..."
          if [ ! -f .gitignore ]; then
            echo "⚠️  No .gitignore found, creating one..."
            cat > .gitignore << 'GITIGNORE_EOF'
          # Dependencies
          node_modules/
          vendor/

          # Environment and secrets
          .env
          .env.local
          .env.*.local
          *.key
          *.pem
          *.p12
          *.pfx
          *secret*
          *password*
          *credentials*
          config/secrets.yml
          config/database.yml

          # IDE
          .vscode/
          .idea/
          *.swp
          *.swo
          *~

          # OS
          .DS_Store
          Thumbs.db

          # Build outputs
          dist/
          build/
          *.log
          GITIGNORE_EOF
            echo "✅ Created default .gitignore"
          else
            echo "✅ .gitignore exists"
          fi

      - name: Install Gitleaks
        run: |
          echo "📦 Installing Gitleaks for secret scanning..."
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz
          tar -xzf gitleaks_8.18.0_linux_x64.tar.gz
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Scan for secrets
        id: gitleaks
        run: |
          echo "🔍 Scanning repository for secrets..."
          if gitleaks detect --no-git --report-path gitleaks-report.json -v; then
            echo "✅ No secrets detected"
            echo "secrets_found=false" >> $GITHUB_OUTPUT
          else
            echo "⚠️  SECRETS DETECTED!"
            echo "secrets_found=true" >> $GITHUB_OUTPUT

            # Extract file paths with secrets
            if [ -f gitleaks-report.json ]; then
              echo "📋 Files with secrets:"
              jq -r '.[].File' gitleaks-report.json | sort -u | tee secret-files.txt
            fi
          fi

      - name: Update .gitignore with secret files
        if: steps.gitleaks.outputs.secrets_found == 'true'
        run: |
          echo "🔒 Adding files with secrets to .gitignore..."

          if [ -f secret-files.txt ]; then
            while IFS= read -r file; do
              # Add file to .gitignore if not already there
              if ! grep -qF "$file" .gitignore 2>/dev/null; then
                echo "$file" >> .gitignore
                echo "  Added: $file"
              fi
            done < secret-files.txt

            echo ""
            echo "⚠️  IMPORTANT: The following files contain secrets and have been added to .gitignore:"
            cat secret-files.txt
            echo ""
            echo "⚠️  You must remove these files from git history using:"
            echo "   git rm --cached <file>"
            echo "   git commit -m 'Remove files with secrets'"
            echo ""
          fi

      - name: Commit .gitignore updates
        if: steps.gitleaks.outputs.secrets_found == 'true'
        run: |
          git config user.name "Gitea Actions"
          git config user.email "actions@gitea.local"

          if git diff --quiet .gitignore; then
            echo "No changes to .gitignore"
          else
            git add .gitignore
            git commit -m "chore: update .gitignore with files containing secrets

          ⚠️  Secret scanner detected sensitive data in the following files:
          $(cat secret-files.txt)

          These files have been added to .gitignore to prevent future commits.
          Please remove them from git history if already committed.

          [skip ci]"

            # Try to push (may fail if no push permissions)
            git push origin ${GITHUB_REF#refs/heads/} || echo "⚠️  Could not push .gitignore update. Please commit manually."
          fi

      - name: Fail if secrets found
        if: steps.gitleaks.outputs.secrets_found == 'true'
        run: |
          echo "❌ BUILD FAILED: Secrets detected in repository"
          echo ""
          echo "🔒 Secret files have been added to .gitignore"
          echo "📝 Please review the files listed above and remove any committed secrets"
          echo "🔄 After fixing, commit and push again"
          exit 1

  build:
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js (if applicable)
        if: hashFiles('package.json') != ''
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        if: hashFiles('package.json') != ''
        run: npm ci || npm install

      - name: Check for vulnerabilities
        if: hashFiles('package.json') != ''
        run: npm audit --audit-level=high || true

      - name: Build
        if: hashFiles('package.json') != ''
        run: |
          if grep -q '"build"' package.json; then
            npm run build
          fi

      - name: Run tests
        if: hashFiles('package.json') != ''
        run: |
          if grep -q '"test"' package.json; then
            npm test
          fi

      - name: Mark as stable
        run: |
          echo "✅ BUILD STATUS: STABLE"
          echo "All checks passed successfully"

      - name: Trigger sync to GitHub
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        run: |
          echo "🔄 Triggering sync to GitHub..."
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          curl -X POST http://home-git-sync-service:48563/api/sync/gitea-to-github \
            -H "Content-Type: application/json" \
            -d "{\"repoName\": \"$REPO_NAME\"}" \
            || echo "⚠️  Sync trigger failed, will sync on next scheduled run"
